export const POST_PLACEHOLDER = [
  {
    id: '123',
    title: 'Test',
    description: 'OWO',
    userId: '123',
    status: 'PUBLISHED',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
  {
    id: '124',
    title: 'Test',
    description: 'OWO',
    userId: '123',
    status: 'PUBLISHED',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
  {
    id: '125',
    title: 'Test',
    description: 'OWO',
    userId: '123',
    status: 'PUBLISHED',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
  {
    id: '126',
    title: 'Test',
    description: 'OWO',
    userId: '123',
    status: 'PUBLISHED',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
  {
    id: '127',
    title: 'Test',
    description: 'OWO',
    userId: '123',
    status: 'PUBLISHED',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
];
